version: "3.3"
services:
  nginx:
    image: nginx:latest
    extra_hosts:
      - "chat:8.8.8.8" 
    deploy:
      replicas: 1
    configs:
      - source: my_config
        target: /etc/nginx/nginx.conf
      - my_other_config
configs:
  my_config:
    file: ./nginx.conf
  my_other_config:
    external: true
