version: "3"
services:
  dev1:
    image: krajewskim/web
    environment:
      - NAME=development_test1
    deploy:
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:test1.dev.yameo.pl"  
      
    networks:
      traefik:
        
networks:
  traefik:
    external: true
